"""onupdate

Revision ID: 20cc512afd7e
Revises: 8cf341e0ad54
Create Date: 2022-07-23 15:17:11.850016

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "20cc512afd7e"
down_revision = "8cf341e0ad54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "group_users_group_id_fkey", "group_users", type_="foreignkey"
    )
    op.drop_constraint(
        "group_users_user_id_fkey", "group_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "group_users", "users", ["user_id"], ["id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "group_users", "groups", ["group_id"], ["id"], onupdate="cascade"
    )
    op.drop_constraint(
        "performers_todo_id_fkey", "performers", type_="foreignkey"
    )
    op.drop_constraint(
        "performers_user_id_fkey", "performers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "performers", "users", ["user_id"], ["id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "performers", "todos", ["todo_id"], ["id"], onupdate="cascade"
    )
    op.drop_constraint("tags_todo_id_fkey", "tags", type_="foreignkey")
    op.create_foreign_key(
        None, "tags", "todos", ["todo_id"], ["id"], onupdate="cascade"
    )
    op.drop_constraint("todos_group_id_fkey", "todos", type_="foreignkey")
    op.drop_constraint("todos_creator_id_fkey", "todos", type_="foreignkey")
    op.create_foreign_key(
        None, "todos", "groups", ["group_id"], ["id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "todos", "users", ["creator_id"], ["id"], onupdate="cascade"
    )
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.create_foreign_key(
        "todos_creator_id_fkey", "todos", "users", ["creator_id"], ["id"]
    )
    op.create_foreign_key(
        "todos_group_id_fkey", "todos", "groups", ["group_id"], ["id"]
    )
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.create_foreign_key(
        "tags_todo_id_fkey", "tags", "todos", ["todo_id"], ["id"]
    )
    op.drop_constraint(None, "performers", type_="foreignkey")
    op.drop_constraint(None, "performers", type_="foreignkey")
    op.create_foreign_key(
        "performers_user_id_fkey", "performers", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "performers_todo_id_fkey", "performers", "todos", ["todo_id"], ["id"]
    )
    op.drop_constraint(None, "group_users", type_="foreignkey")
    op.drop_constraint(None, "group_users", type_="foreignkey")
    op.create_foreign_key(
        "group_users_user_id_fkey", "group_users", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "group_users_group_id_fkey",
        "group_users",
        "groups",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###
