"""added ondelete to group_user

Revision ID: 2549d5e84a31
Revises: ebb28220e839
Create Date: 2022-08-12 14:59:14.704390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2549d5e84a31'
down_revision = 'ebb28220e839'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_users_group_id_fkey', 'group_users', type_='foreignkey')
    op.drop_constraint('group_users_user_id_fkey', 'group_users', type_='foreignkey')
    op.create_foreign_key(None, 'group_users', 'groups', ['group_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'group_users', 'users', ['user_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_users', type_='foreignkey')
    op.drop_constraint(None, 'group_users', type_='foreignkey')
    op.create_foreign_key('group_users_user_id_fkey', 'group_users', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('group_users_group_id_fkey', 'group_users', 'groups', ['group_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
