"""change todo primary key to message id

Revision ID: 27e04b5b70a3
Revises: 26996624fe81
Create Date: 2022-07-25 20:28:01.932409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27e04b5b70a3"
down_revision = "26996624fe81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "message_id")
    op.alter_column("todos", "id", type_=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column(
            "message_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
