"""added statuses

Revision ID: 2cb58a934315
Revises: ccee7613a4c7
Create Date: 2022-08-04 19:24:24.544858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cb58a934315"
down_revision = "ccee7613a4c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("todos", sa.Column("status_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "todos", "statuses", ["status_id"], ["id"], ondelete="set null"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_column("todos", "status_id")
    op.drop_table("statuses")
    # ### end Alembic commands ###
