"""empty message

Revision ID: 3477c62d4b2c
Revises: 83a633e0e58f
Create Date: 2022-07-21 16:56:44.324618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3477c62d4b2c"
down_revision = "83a633e0e58f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "telegram_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.create_unique_constraint(None, "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "telegram_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
