"""added ondelete to performers

Revision ID: 3e1d6019bba7
Revises: 8860ffd41b80
Create Date: 2022-08-12 15:06:34.479929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1d6019bba7'
down_revision = '8860ffd41b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('performers_todo_id_todo_group_id_fkey', 'performers', type_='foreignkey')
    op.create_foreign_key(None, 'performers', 'todos', ['todo_id', 'todo_group_id'], ['id', 'group_id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performers', type_='foreignkey')
    op.create_foreign_key('performers_todo_id_todo_group_id_fkey', 'performers', 'todos', ['todo_id', 'todo_group_id'], ['id', 'group_id'])
    # ### end Alembic commands ###
