"""unique performers

Revision ID: 6e97bda2d2f1
Revises: 4ef9bbd25400
Create Date: 2022-07-25 20:49:34.478091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e97bda2d2f1'
down_revision = '4ef9bbd25400'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'performers', ['todo_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performers', type_='unique')
    # ### end Alembic commands ###
