"""empty message

Revision ID: 750633fade02
Revises: 3477c62d4b2c
Create Date: 2022-07-21 17:05:28.792789

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "750633fade02"
down_revision = "3477c62d4b2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_telegram_id_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_telegram_id_key", "users", ["telegram_id"])
    # ### end Alembic commands ###
