"""empty message

Revision ID: 83a633e0e58f
Revises: 7bb74eda655e
Create Date: 2022-07-21 16:53:27.113810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83a633e0e58f"
down_revision = "7bb74eda655e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
