"""added group_user

Revision ID: 920436bdfef9
Revises: d75eb5af287f
Create Date: 2022-07-23 12:48:44.976561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "920436bdfef9"
down_revision = "d75eb5af287f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id", "group_id"),
        sa.UniqueConstraint("user_id", "group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_users")
    # ### end Alembic commands ###
