"""added deadline to todo

Revision ID: b819219f2077
Revises: 3e1d6019bba7
Create Date: 2022-08-12 18:05:26.837502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b819219f2077"
down_revision = "3e1d6019bba7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("deadline", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "deadline")
    # ### end Alembic commands ###
