"""create additional info

Revision ID: ebb28220e839
Revises: f6a821cbd54a
Create Date: 2022-08-11 13:44:15.553010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb28220e839'
down_revision = 'f6a821cbd54a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_info',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('additional_info_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'todos', 'additional_info', ['additional_info_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'additional_info_id')
    op.drop_table('additional_info')
    # ### end Alembic commands ###
