"""fix performers

Revision ID: f6a821cbd54a
Revises: 25557219a968
Create Date: 2022-08-08 20:58:34.936430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6a821cbd54a"
down_revision = "25557219a968"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "todos", ["id", "group_id"])
    op.add_column(
        "performers",
        sa.Column("todo_group_id", sa.BigInteger(), nullable=True),
    )
    op.drop_constraint(
        "performers_todo_id_user_id_key", "performers", type_="unique"
    )
    op.create_unique_constraint(
        None, "performers", ["todo_id", "todo_group_id", "user_id"]
    )
    op.drop_constraint(
        "performers_todo_id_fkey", "performers", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "performers",
        "todos",
        ["todo_id", "todo_group_id"],
        ["id", "group_id"],
    )
    op.add_column(
        "tags", sa.Column("todo_group_id", sa.BigInteger(), nullable=True)
    )
    op.drop_constraint("tags_todo_id_fkey", "tags", type_="foreignkey")
    op.create_foreign_key(
        None, "tags", "todos", ["todo_id", "todo_group_id"], ["id", "group_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="unique")
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.create_foreign_key(
        "tags_todo_id_fkey",
        "tags",
        "todos",
        ["todo_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("tags", "todo_group_id")
    op.drop_constraint(None, "performers", type_="foreignkey")
    op.create_foreign_key(
        "performers_todo_id_fkey",
        "performers",
        "todos",
        ["todo_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "performers", type_="unique")
    op.create_unique_constraint(
        "performers_todo_id_user_id_key", "performers", ["todo_id", "user_id"]
    )
    op.drop_column("performers", "todo_group_id")
    # ### end Alembic commands ###
